### ISSUE TITLE
Jumpy ordered list items in Callouts

### ISSUE THREAD

**Issue by FeralFlora** [callumhackett/obsidian_polka_theme#9]
When editing a list item, the list item jumps to the left upon adding a space to start typing. List items with and without text do not remain aligned. See the gif of the behavior:

![Obsidian_jumpy_list](https://user-images.githubusercontent.com/33608083/222414608-bc6a9fe5-55b9-4cbb-b90d-f7086e456091.gif)

**Comment by callumhackett** [comment]
A quick fix for this is available in v1.3.6. For now, I've had to sacrifice the wider-than-default padding that Polka added to blockquotes, as there is a complex underlying issue here around how Obsidian recognizes and renders lists. If I can return the wider padding in a future version, I will, but the current compromise is more functional.

**Comment by FeralFlora** [comment]
Thanks for the quick fix, you're right, it's more functional now. Hopefully the wider padding will be possible later, but this is also fine for me now as is.
